use std::fs;
use std::path::{Path, PathBuf};

use serde_yaml_ng::Value;

use crate::model::{ArtifactKind, FileFormat, Ownership, Safety, ScanReport};
use crate::provider::{HomeScope, ScanContext};

use super::support::{
    FindingSpec, RewriteSpec, add_empty_dir, add_path, add_rewrite, resolve_file,
};

const MANAGED_PLUGIN_MARKER: &str = "Managed by Orca. Do not edit; changes may be overwritten.";
const KIMI_START: &str = "# >>> orca-managed-kimi-hooks (managed by Orca; do not edit) >>>";
const KIMI_END: &str = "# <<< orca-managed-kimi-hooks <<<";

const HOOK_STEMS: &[&str] = &[
    "claude-hook",
    "claude-statusline",
    "openclaude-hook",
    "cursor-hook",
    "codex-hook",
    "copilot-hook",
    "gemini-hook",
    "antigravity-hook",
    "antigravity-pre-invocation",
    "antigravity-post-invocation",
    "antigravity-stop",
    "antigravity-pre-tool-use",
    "antigravity-post-tool-use",
    "droid-hook",
    "command-code-hook",
    "grok-hook",
    "kimi-hook",
    "devin-hook",
];

pub(crate) fn inspect(context: &ScanContext, configs_were_readable: bool, report: &mut ScanReport) {
    for scope in context.home_scopes() {
        inspect_amp(&scope, report);
        inspect_hermes(context, &scope, report);
        inspect_kimi(context, &scope, report);
        inspect_hook_scripts(&scope, configs_were_readable, report);
        inspect_remote_runtime(context, &scope, report);
    }
}

fn inspect_hook_scripts(scope: &HomeScope, configs_were_readable: bool, report: &mut ScanReport) {
    let root = scope.home.join(".orca/agent-hooks");
    let Ok(entries) = fs::read_dir(&root) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_ascii_lowercase();
        if name == "grok-owners" {
            inspect_grok_owners(&path, scope, report);
            continue;
        }
        let recognized = HOOK_STEMS.iter().any(|stem| {
            name == *stem
                || name.starts_with(&format!("{stem}."))
                || name.starts_with(&format!("{stem}-"))
        });
        let safety = if recognized && configs_were_readable {
            Safety::Automatic
        } else {
            Safety::ReviewRequired
        };
        add_path(
            report,
            &path,
            FindingSpec {
                kind: ArtifactKind::ManagedHook,
                ownership: Ownership::ProviderOwned,
                safety,
                description: if recognized {
                    "Orca-managed agent hook or ownership record"
                } else {
                    "Unrecognized file in Orca's managed hook directory"
                },
                evidence: if recognized {
                    "the exact filename family is generated by an Orca integration"
                } else {
                    "the parent directory is Orca-owned, but the filename is not recognized"
                },
                id_prefix: "remove-agent-hook",
                scope: scope.kind,
                actionable: true,
            },
        );
        if recognized {
            let dependencies = integration_dependencies(&name, report);
            if let Some(action) = report
                .findings
                .last_mut()
                .and_then(|finding| finding.action.as_mut())
            {
                action.depends_on = dependencies;
            }
        }
    }
    add_empty_dir(
        report,
        &root,
        ArtifactKind::ManagedHook,
        scope.kind,
        "remove empty Orca agent hook directory",
    );
}

fn inspect_grok_owners(root: &Path, scope: &HomeScope, report: &mut ScanReport) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        let token = entry
            .file_name()
            .to_string_lossy()
            .strip_prefix("owner-")
            .and_then(|name| name.strip_suffix(".json"))
            .map(str::to_owned);
        let value = fs::read(&path)
            .ok()
            .and_then(|bytes| serde_json::from_slice::<serde_json::Value>(&bytes).ok());
        let valid = token.as_deref().is_some_and(|token| {
            value.as_ref().is_some_and(|value| {
                value.get("token").and_then(serde_json::Value::as_str) == Some(token)
                    && value
                        .get("pid")
                        .and_then(serde_json::Value::as_u64)
                        .is_some_and(|pid| pid > 0)
            })
        });
        add_path(
            report,
            &path,
            FindingSpec {
                kind: ArtifactKind::RuntimeState,
                ownership: Ownership::ProviderOwned,
                safety: if valid {
                    Safety::ReviewRequired
                } else {
                    Safety::Automatic
                },
                description: "Orca Grok hook owner record",
                evidence: if valid {
                    "the ownership record is well formed and may name a live Orca process"
                } else {
                    "the Orca-owned record is malformed and cannot prove a live owner"
                },
                id_prefix: "remove-grok-owner",
                scope: scope.kind,
                actionable: true,
            },
        );
    }
    add_empty_dir(
        report,
        root,
        ArtifactKind::RuntimeState,
        scope.kind,
        "remove empty Grok hook owner directory",
    );
}

fn inspect_amp(scope: &HomeScope, report: &mut ScanReport) {
    let path = scope.home.join(".config/amp/plugins/orca-agent-status.ts");
    inspect_marked_owned_file(
        &path,
        scope,
        ArtifactKind::Plugin,
        "Orca-managed Amp plugin",
        report,
    );
}

fn inspect_hermes(context: &ScanContext, scope: &HomeScope, report: &mut ScanReport) {
    let home = environment_home(context, scope, "HERMES_HOME", ".hermes");
    rewrite_hermes_config(&home.join("config.yaml"), scope, report);
    let plugin = home.join("plugins/orca-status");
    let manifest = fs::read_to_string(plugin.join("plugin.yaml")).unwrap_or_default();
    let init = fs::read_to_string(plugin.join("__init__.py")).unwrap_or_default();
    if manifest.contains(MANAGED_PLUGIN_MARKER) && init.contains(MANAGED_PLUGIN_MARKER) {
        add_path(
            report,
            &plugin,
            FindingSpec {
                kind: ArtifactKind::Plugin,
                ownership: Ownership::ProviderOwned,
                safety: Safety::Automatic,
                description: "Orca-managed Hermes plugin",
                evidence: "both plugin files contain Orca's managed-content marker",
                id_prefix: "remove-hermes-plugin",
                scope: scope.kind,
                actionable: true,
            },
        );
        let dependencies = integration_dependencies("hermes", report);
        if let Some(action) = report
            .findings
            .last_mut()
            .and_then(|finding| finding.action.as_mut())
        {
            action.depends_on = dependencies;
        }
    } else if plugin.exists() {
        add_path(
            report,
            &plugin,
            FindingSpec {
                kind: ArtifactKind::Plugin,
                ownership: Ownership::Attributed,
                safety: Safety::Informational,
                description: "Unverified Hermes orca-status plugin",
                evidence: "the expected path exists but both ownership markers were not found",
                id_prefix: "unverified-hermes-plugin",
                scope: scope.kind,
                actionable: false,
            },
        );
    }
    inspect_backup(
        &home.join("config.yaml.bak"),
        scope,
        "Hermes configuration backup",
        report,
    );
}

fn integration_dependencies(name: &str, report: &ScanReport) -> Vec<String> {
    let (product, path_marker) = if name.contains("openclaude") {
        ("openclaude", "/.openclaude/")
    } else if name.contains("claude") {
        ("claude code", "/.claude/")
    } else if name.contains("antigravity") {
        ("antigravity", "/.gemini/config/")
    } else if name.contains("command-code") {
        ("command code", "/.commandcode/")
    } else if name.contains("copilot") {
        ("copilot", "/.copilot/")
    } else if name.contains("codex") {
        ("codex", "/.codex/")
    } else if name.contains("cursor") {
        ("cursor", "/.cursor/")
    } else if name.contains("gemini") {
        ("gemini", "/.gemini/")
    } else if name.contains("droid") {
        ("droid", "/.factory/")
    } else if name.contains("grok") {
        ("grok", "/.grok/")
    } else if name.contains("kimi") {
        ("kimi", "/.kimi-code/")
    } else if name.contains("devin") {
        ("devin", "/devin/")
    } else if name.contains("hermes") {
        ("hermes", "/.hermes/")
    } else {
        return Vec::new();
    };
    report
        .findings
        .iter()
        .filter(|finding| {
            let relevant_kind = finding.kind == ArtifactKind::ConfigMutation
                || (product == "codex"
                    && finding.kind == ArtifactKind::TrustEntry
                    && !finding.evidence.contains("; 0 hook trust block"));
            relevant_kind
                && (finding.description.to_ascii_lowercase().contains(product)
                    || finding
                        .path
                        .to_string_lossy()
                        .replace('\\', "/")
                        .contains(path_marker))
        })
        .filter_map(|finding| finding.action.as_ref().map(|action| action.id.clone()))
        .collect()
}

fn rewrite_hermes_config(configured: &Path, scope: &HomeScope, report: &mut ScanReport) {
    let Some(path) = resolve_file(configured, report) else {
        return;
    };
    let bytes = match fs::read(&path) {
        Ok(bytes) => bytes,
        Err(error) => {
            report
                .warnings
                .push(format!("could not read {}: {error}", path.display()));
            return;
        }
    };
    let mut root: Value = match serde_yaml_ng::from_slice(&bytes) {
        Ok(value) => value,
        Err(error) => {
            report.warnings.push(format!(
                "could not parse Hermes YAML {}: {error}",
                path.display()
            ));
            return;
        }
    };
    let Some(plugins) = root.get_mut("plugins").and_then(Value::as_mapping_mut) else {
        return;
    };
    let key = Value::String("enabled".to_owned());
    let (mutations, empty) = {
        let Some(enabled) = plugins.get_mut(&key).and_then(Value::as_sequence_mut) else {
            return;
        };
        let before = enabled.len();
        enabled.retain(|value| value.as_str() != Some("orca-status"));
        if enabled.len() == before {
            return;
        }
        (before - enabled.len(), enabled.is_empty())
    };
    if empty {
        plugins.remove(&key);
    }
    let replacement = match serde_yaml_ng::to_string(&root) {
        Ok(value) => value.into_bytes(),
        Err(error) => {
            report
                .warnings
                .push(format!("could not serialize Hermes YAML: {error}"));
            return;
        }
    };
    add_rewrite(
        report,
        path,
        &bytes,
        replacement,
        RewriteSpec {
            kind: ArtifactKind::ConfigMutation,
            safety: Safety::Automatic,
            description: "Disable the Orca-managed Hermes plugin".to_owned(),
            evidence: "plugins.enabled contains the exact Orca plugin name orca-status".to_owned(),
            id_prefix: "rewrite-hermes-config",
            scope: scope.kind,
            format: FileFormat::Yaml,
            mutation_count: mutations,
        },
    );
}

fn inspect_kimi(context: &ScanContext, scope: &HomeScope, report: &mut ScanReport) {
    let home = environment_home(context, scope, "KIMI_CODE_HOME", ".kimi-code");
    let configured = home.join("config.toml");
    let Some(path) = resolve_file(&configured, report) else {
        inspect_backup(
            &home.join("config.toml.bak"),
            scope,
            "Kimi configuration backup",
            report,
        );
        return;
    };
    let bytes = match fs::read(&path) {
        Ok(bytes) => bytes,
        Err(error) => {
            report
                .warnings
                .push(format!("could not read {}: {error}", path.display()));
            return;
        }
    };
    let Ok(text) = std::str::from_utf8(&bytes) else {
        report
            .warnings
            .push(format!("{} is not UTF-8", path.display()));
        return;
    };
    if let Some(replacement) = remove_kimi_block(text) {
        if replacement.parse::<toml_edit::DocumentMut>().is_err() {
            report.warnings.push(format!(
                "refusing invalid cleaned Kimi TOML {}",
                path.display()
            ));
        } else {
            add_rewrite(
                report,
                path,
                &bytes,
                replacement.into_bytes(),
                RewriteSpec {
                    kind: ArtifactKind::ConfigMutation,
                    safety: Safety::Automatic,
                    description: "Remove Orca's managed Kimi hook block".to_owned(),
                    evidence: "the block is bounded by Orca's exact start and end markers"
                        .to_owned(),
                    id_prefix: "rewrite-kimi-config",
                    scope: scope.kind,
                    format: FileFormat::Toml,
                    mutation_count: 1,
                },
            );
        }
    }
    inspect_backup(
        &home.join("config.toml.bak"),
        scope,
        "Kimi configuration backup",
        report,
    );
}

fn remove_kimi_block(text: &str) -> Option<String> {
    let start = text.find(KIMI_START)?;
    let end = text[start..].find(KIMI_END)? + start + KIMI_END.len();
    let mut remove_start = start;
    while remove_start > 0 && text.as_bytes()[remove_start - 1] == b'\n' {
        remove_start -= 1;
        if remove_start == 0 || text.as_bytes()[remove_start - 1] != b'\n' {
            break;
        }
    }
    let mut remove_end = end;
    if text[remove_end..].starts_with("\r\n") {
        remove_end += 2;
    } else if text[remove_end..].starts_with('\n') {
        remove_end += 1;
    }
    let mut result = String::with_capacity(text.len() - (remove_end - remove_start));
    result.push_str(&text[..remove_start]);
    result.push_str(&text[remove_end..]);
    Some(result)
}

fn inspect_backup(path: &Path, scope: &HomeScope, description: &str, report: &mut ScanReport) {
    if path.exists() {
        add_path(
            report,
            path,
            FindingSpec {
                kind: ArtifactKind::Backup,
                ownership: Ownership::Attributed,
                safety: Safety::ReviewRequired,
                description,
                evidence: "Orca creates this exact .bak sidecar before changing the configuration",
                id_prefix: "review-config-backup",
                scope: scope.kind,
                actionable: true,
            },
        );
    }
}

fn inspect_marked_owned_file(
    path: &Path,
    scope: &HomeScope,
    kind: ArtifactKind,
    description: &str,
    report: &mut ScanReport,
) {
    let Ok(content) = fs::read_to_string(path) else {
        return;
    };
    let managed = content.contains(MANAGED_PLUGIN_MARKER);
    add_path(
        report,
        path,
        FindingSpec {
            kind,
            ownership: if managed {
                Ownership::ProviderOwned
            } else {
                Ownership::Attributed
            },
            safety: if managed {
                Safety::Automatic
            } else {
                Safety::Informational
            },
            description,
            evidence: if managed {
                "the file contains Orca's managed-content marker"
            } else {
                "the expected filename exists without Orca's ownership marker"
            },
            id_prefix: "orca-managed-plugin",
            scope: scope.kind,
            actionable: managed,
        },
    );
}

fn inspect_remote_runtime(context: &ScanContext, scope: &HomeScope, report: &mut ScanReport) {
    let root = scope.home.join(".orca-remote");
    let Ok(entries) = fs::read_dir(&root) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let name = entry.file_name().to_string_lossy().into_owned();
        let recognized = name.starts_with("relay-")
            || name.starts_with("orcad-")
            || name.contains("tombstone")
            || name.contains("pending-delete");
        let stale =
            recognized && super::support::is_older_than(&entry.path(), context.stale_after_days);
        add_path(
            report,
            &entry.path(),
            FindingSpec {
                kind: ArtifactKind::RemoteRuntime,
                ownership: Ownership::ProviderOwned,
                safety: if stale {
                    Safety::Automatic
                } else if recognized {
                    Safety::ReviewRequired
                } else {
                    Safety::Informational
                },
                description: "Orca SSH remote runtime version or GC residue",
                evidence: if stale {
                    "the generated name matches Orca remote runtime state and exceeds retention"
                } else if recognized {
                    "the generated name matches Orca remote runtime state but may still be active"
                } else {
                    "the path is under .orca-remote but its name is not recognized"
                },
                id_prefix: "orca-remote-runtime",
                scope: scope.kind,
                actionable: recognized,
            },
        );
    }
    add_empty_dir(
        report,
        &root,
        ArtifactKind::RemoteRuntime,
        scope.kind,
        "remove empty Orca remote runtime root",
    );
}

fn environment_home(
    context: &ScanContext,
    scope: &HomeScope,
    variable: &str,
    fallback: &str,
) -> PathBuf {
    if scope.kind == crate::model::ScopeKind::Local && context.honor_environment {
        if let Some(path) = context.environment_path(variable) {
            return path;
        }
    }
    scope.home.join(fallback)
}
